/** Editor chrome copy — insert rail, bubble toolbar, wrap picker, image toolbar, sticker picker. */
export const editorChrome = {
  rail: {
    label: 'Insert',
    text: 'Text',
    picture: 'Picture',
    sticker: 'Sticker',
    cover: 'Cover',
    hints: { picture: '⇧⌘I', sticker: '⇧⌘S' },
  },
  bubble: {
    label: 'Formatting',
    kindMenu: 'Block kind',
    kinds: { title: 'Title', heading: 'Heading', body: 'Body', quote: 'Quote', caption: 'Caption' },
    kindHints: { title: '⌘⌥1', heading: '⌘⌥2', body: '⌘⌥3', quote: '⌘⌥4', caption: '⌘⌥5' },
    format: { bold: 'Bold', italic: 'Italic', underline: 'Underline', strikeThrough: 'Strikethrough', link: 'Link', list: 'List' },
    formatHints: { bold: '⌘B', italic: '⌘I', underline: '⌘U', strikeThrough: '⇧⌘X', link: '', list: '⇧⌘8' },
  },
  wrap: {
    label: 'Text wrap',
    auto: 'Wrap around',
    break: 'Above and below',
    behind: 'Behind text',
    front: 'In front',
  },
  image: {
    label: 'Picture',
    shape: 'Shape',
    shapes: { square: 'Square', rounded: 'Rounded', circle: 'Circle', heart: 'Heart' },
    cornersValue: (r: number) => (r === 0 ? 'Rounded corners' : `Rounded corners · ${r}`),
    reframe: 'Reposition inside the shape',
    reframeOn: 'Drag to reposition · scroll to zoom · Esc when done',
    zoom: 'Zoom',
    opacity: 'Opacity',
    polaroid: 'Polaroid frame',
    replace: 'Replace picture',
    remove: 'Remove picture',
  },
  sticker: {
    title: 'Add a sticker',
    emoji: 'Emoji',
    stickers: 'Stickers',
    searchEmoji: 'Search emoji',
    systemHint: 'Ctrl Cmd Space also opens emoji anywhere',
    noMatch: 'No emoji match that',
    close: 'Close',
    grid: 'Built-in stickers',
    emojiGrid: 'Emoji',
  },
  /** Display names of the built-in sticker set, keyed by sticker id. */
  stickerNames: {
    'washi-terracotta': 'Striped washi tape',
    'washi-sage-dots': 'Dotted washi tape',
    'washi-mustard': 'Plain washi tape',
    'paper-clip': 'Paper clip',
    star: 'Star',
    'star-cluster': 'Stars',
    heart: 'Heart',
    'double-heart': 'Hearts',
    arrow: 'Arrow',
    'arrow-curved': 'Curved arrow',
    'doodle-loop': 'Loop',
    'doodle-underline': 'Underline',
    'coffee-ring': 'Coffee ring',
    'date-stamp': 'Date stamp',
    sun: 'Sun',
    leaf: 'Leaf',
  },
} as const
