/** Page editor copy (surface 3). Sentence case, short, warm, no exclamation marks. */
export const editor = {
  back: 'Back to book',
  changeDate: 'Change date',
  pageOf: (n: number, total: number) => `Page ${n} of ${total}`,
  addPage: 'Add a page',
  pageAdded: 'Page added',
  prevPage: 'Previous page',
  nextPage: 'Next page',
  /** Header title field + the empty title-kind block, rotating by local hour. */
  titlePlaceholder: { morning: 'This morning', afternoon: 'This afternoon', night: 'Tonight' },
  placeholder: {
    heading: 'Heading',
    body: 'Write here',
    quote: 'A line worth keeping',
    caption: 'Caption',
  },
  /** Gentle prompts for an empty body block (Settings → Writing prompts). */
  prompts: [
    'What stayed with you today',
    'Something small that went well',
    'A conversation worth keeping',
    'What you noticed on the way',
    'One thing to let go of',
    'What you are looking forward to',
    'Who you were glad to see',
    'A place you would go back to',
    'Something you learned by accident',
    'What the weather did to the day',
    'A sentence someone said',
    'What you made with your hands',
    'The best thing you ate',
    'A worry that turned out fine',
    'What you would tell yourself this morning',
    'Something you want to remember in a year',
    'A sound from today',
    'What you are grateful for, quietly',
    'A question you are still turning over',
    'How the day ended',
    'Something that made you laugh',
    'What you read, watched or listened to',
    'A small kindness, given or received',
    'What tomorrow could use',
  ],
  save: {
    pending: 'Unsaved changes',
    saving: 'Saving',
    saved: 'Saved just now',
    failed: "Couldn't save — your writing is still here",
    retry: 'Try again',
  },
  words: (n: number, min: number) => `${n} ${n === 1 ? 'word' : 'words'} · about ${Math.max(1, min)} min to read`,
  overflow: {
    label: 'Text continues off the page',
    action: 'Continue on next page',
  },
  removed: { image: 'Picture removed', sticker: 'Sticker removed', text: 'Text removed' },
  undo: 'Undo',
  duplicated: 'Duplicated',
  continued: 'Continued on the next page',
  image: {
    tooBig: 'That picture is too large to keep',
    unsupported: "That file isn't a picture",
    failed: "Couldn't read that picture",
    dropHere: 'Drop to place',
    replace: 'Choose a picture',
  },
  link: {
    prompt: 'Link address',
  },
  zoom: { fit: 'Fit to window', in: 'Zoom in', out: 'Zoom out' },
  size: (w: number, h: number) => `${w} × ${h}`,
  rotation: (deg: number) => `${Math.round(deg)}°`,
  a11y: {
    editor: 'Page editor',
    page: 'Page',
    document: 'Document',
    title: 'Title',
    grab: 'Move text',
    selection: 'Selection',
    resize: 'Resize',
    autosave: 'Autosave',
    dropGhost: 'Drop target',
    textBlock: 'Text block',
    imageBlock: 'Picture',
    stickerBlock: 'Sticker',
    rotate: 'Rotate',
    wordCount: 'Word count',
    overflowLine: 'Bottom of the page',
  },
} as const
