/** Front page copy (nav, hero, the scroll story, marquee, features, demo, quotes, the way in). */
export const landing = {
  nav: {
    practice: 'Practice',
    features: 'Features',
    start: 'Start writing',
    open: 'Open your shelf',
  },
  hero: {
    eyebrow: 'Every entry is a book',
    line1: 'Write it down.',
    line2: 'Put it on the shelf.',
    lede: 'Brawley keeps your days as real books on a real shelf. Photos, video and long, unhurried writing — bound by day, kept on your own computer, yours.',
    start: 'Start writing — free',
    how: 'See how it works',
    note: 'No account · Kept in a file you choose · Nothing is sent anywhere',
    noteBrowser: 'No account · Kept in this browser · Nothing is sent anywhere',
    hoverHint: 'Hover a spine',
  },
  /** the way in, by where the journal is */
  entry: {
    start: 'Start writing — free',
    open: 'Open an existing journal',
    openShelf: 'Open your shelf',
    another: 'Open another journal',
    welcomeBack: 'Welcome back',
    reopen: (name: string) => `Open ${name}`,
    reopenHint: 'Your browser asks for one click before it opens the file again.',
    different: 'Use a different file',
    readFailed: (name: string) => `${name} couldn't be read. Choose it again, or start a new journal.`,
    notAJournal: "That file isn't a Brawley journal",
    choosing: 'Choosing a file',
    opening: 'Opening',
    browserNote: 'This browser cannot keep a file open, so the journal will stay in the browser. In Chrome or Edge it can live in a file you choose.',
  },
  story: {
    wordA: 'A day',
    wordB: 'A page',
    date: 'Tuesday, 9 September',
    meta: 'Daily · p. 214',
    times: ['07:40', '12:15', '18:40', '21:12'],
    lines1: ['Took the ferry across instead of the bridge.', 'Nobody talks on the 7:40 — everyone just watches', 'the water go from grey to green.'],
    photo: 'photo · ferry deck, 12:15',
    lines2: ['Walked home the slow way. The jacaranda is out,', 'a week later than last year. I checked.'],
    voice: 'Voice note · Nour called',
    voiceMeta: '2:14 · transcribed',
    stats: '312 words · 1 photo · 1 voice note',
    bound: 'Bound',
    hint: 'Keep scrolling — watch the day settle onto the page',
  },
  marquee: {
    eyebrow: 'The life of a page',
    lines: ['Lived', 'Written', 'Shelved', 'Reread.'],
  },
  features: {
    eyebrow: 'The practice',
    title: 'Built for slow, honest writing.',
    hint: 'Scroll — one page at a time',
    panels: [
      {
        n: '01',
        title: ['A dotted page,', 'anything goes'],
        body: "Drop text, photos, video and stickers anywhere on the grid. Nudge them into place; the words wrap around. It's a scrapbook that happens to be searchable.",
      },
      {
        n: '02',
        title: ['A bookmark,', 'not a nag'],
        body: "One quiet question tucked into today's page. Answer it in a sentence or a chapter, or pull the bookmark out — the page stays yours either way.",
      },
      {
        n: '03',
        title: ['Say it', 'instead'],
        body: 'Some days the hands are busy. Talk on the walk home and Brawley writes it onto the page as you go — the recording stays tucked in the margin, the words become a paragraph.',
      },
      {
        n: '04',
        title: ['The year,', 'bound'],
        body: "Each December the year's books are bound into one thick volume: the words you used most, the places you wrote from, the days you came back to. It goes on the shelf next to the others.",
      },
    ],
    page: {
      title: 'Ferry mornings',
      body: 'Took the ferry across instead of the bridge. Nobody talks on the 7:40 — everyone just watches the water go from grey to green. Bought two pastéis and ate both before the tram came.',
      photo: 'photo',
      quote: '“The water goes green when nobody is looking at it.”',
      chips: ['Text', 'Photo', 'Sticker'],
      sticker: 'good day',
    },
    bookmark: {
      date: 'Tue · 9 Sept',
      question: "What did you almost say today, and didn't?",
      answer: 'Answer',
      pull: 'Pull the bookmark',
    },
    voice: {
      title: 'Walk home',
      meta: '2:14 · transcribing',
      text: '…and I think the thing I keep circling back to is that I wasn’t angry, I was tired, which is a different ',
      faded: 'problem with a different',
    },
    bound: {
      spine: 'Two thousand twenty-five',
      cover: ['2025', 'in review'],
      books: ['Garden', 'Lisbon & after', 'Dreams'],
      stats: [['214', 'days'], ['61k', 'words'], ['11', 'books']],
    },
  },
  demo: {
    title: 'Your books, on one shelf.',
    a11y: 'Interactive Brawley demo — hover to pause, click the sidebar to explore',
    menu: ['File', 'Edit', 'View', 'Window', 'Help'],
    battery: '47%',
    clock: 'Tue 9 Sept  9:12 PM',
    search: 'Search every page',
    nav: { today: 'Today', books: 'Books', prompts: 'Prompts', memories: 'On this day', review: 'Year in review' },
    booksCount: '5',
    sidebarBooks: 'Books',
    shelf: [
      ['Daily', '214', '#1E3A2F'],
      ['Lisbon & after', '23', '#D9962B'],
      ['Garden', '41', '#6E8F6B'],
      ['Letters to Nour', '9', '#A8664A'],
      ['Dreams', '17', '#7C8FA6'],
    ],
    settings: 'Settings',
    today: {
      title: 'Tuesday, 9 September',
      meta: 'Daily · page 214 · 9:12 pm',
      speak: 'Speak instead',
      p1: 'Long day, but the good kind. Walked home the slow way past the school and the jacaranda is finally out — a week later than last year, I checked.',
      photo: 'photo · jacaranda, 18:40',
      video: 'video · 0:12',
      play: '▶ 0:12',
      p2: "Nour called. We didn't talk about the thing. I think that was the right call for tonight.",
      voice: 'Voice note · walk home',
      voiceMeta: '2:14 · transcribed',
      words: '312 words',
      saved: 'Autosaved just now',
    },
    books: {
      title: 'Books',
      meta: '5 books · 304 pages · since March 2024',
      newBook: '+ New book',
      items: [
        ['Vol. I', 'Daily', '214 pages · today', '#1E3A2F', '#142820', '#F3EFE6', 440],
        ['Travel', 'Lisbon & after', '23 pages · Mon', '#D9962B', '#B57A1F', '#1E3A2F', 380],
        ['Outside', 'Garden', '41 pages · Wed', '#6E8F6B', '#587455', '#F3EFE6', 400],
        ['Private', 'Letters to Nour', '9 pages · Aug', '#A8664A', '#8A5039', '#F3EFE6', 340],
        ['Night', 'Dreams', '17 pages · Sat', '#7C8FA6', '#61738A', '#F3EFE6', 360],
      ] as const,
    },
    review: {
      title: 'Year in review',
      meta: '2025 so far · 214 days written · 61,402 words',
      years: ['2025', '2024', 'All time'],
      days: 'Days written',
      pct: '59%',
      of: '214 of 365',
      run: 'Longest run · 31 days',
      quiet: 'Quietest month · Feb',
      where: 'Where the words went',
      pages: 'Pages',
      words: 'Words',
      split: [['Daily', '70%', '#1E3A2F'], ['Garden', '13%', '#6E8F6B'], ['Lisbon & after', '8%', '#D9962B'], ['Dreams', '6%', '#7C8FA6']],
      perMonth: 'Words per month',
      months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
      bars: [46, 22, 58, 64, 80, 71, 88, 100, 34],
      kept: 'Words you kept using',
      cloud: [['light', 34, '#1E3A2F'], ['enough', 24, '#3B4F45'], ['home', 40, '#D9962B'], ['quietly', 22, '#6B7A72'], ['again', 30, '#1E3A2F'], ['tomorrow', 20, '#3B4F45'], ['garden', 26, '#6E8F6B'], ['Nour', 22, '#6B7A72']] as const,
      binding: 'Binding progress',
      goal1: '2025 — bound in December',
      goal1Meta: '113d · 59%',
      goal2: 'Photos & video kept',
      goal2Meta: '412 · 2.1 GB',
    },
  },
  quotes: [
    { text: "“I've tried a dozen journaling apps. This is the first one that didn't make me feel behind.”", who: 'Maya R. — writes most mornings' },
    { text: "“Pulling a book off the shelf and flipping to a Tuesday from two years ago. That's the whole app for me.”", who: 'Dan K. — nurse, night shifts' },
    { text: "“I read my 2024 book on New Year's Day and cried a little. In a good way.”", who: 'Priya S. — three books and counting' },
  ],
  cta: {
    title: 'Keep the days.',
    lede: "A shelf you'll still be adding to in twenty years.",
    note: 'No account · Your journal is a file on your computer · Export everything, any time',
  },
  footer: {
    year: '© 2026',
  },
  /** the hero shelf: the books on it, and the ghost slot */
  shelf: {
    books: [
      { title: 'January, mostly rain', date: 'Sunday, 12 January 2026', w: 28, cover: '#c15f3c', cover2: '#9a4a2e', ink: '#f4efe6', jz: -0.21 },
      { title: 'Nour', date: 'Friday, 24 January 2026', w: 18, cover: '#6b4a63', cover2: '#4d3347', ink: '#f4efe6', jz: 0.12 },
      { title: 'Ferry mornings', date: 'Monday, 3 February 2026', w: 36, cover: '#8a9a7b', cover2: '#6b7a5f', ink: '#f4efe6', jz: 0.3 },
      { title: 'Untitled', date: 'Tuesday, 18 February 2026', w: 16, cover: '#e5bd6a', cover2: '#d9a441', ink: '#2b2620', jz: -0.08, blank: true },
      { title: 'Garden, year two', date: 'Saturday, 14 March 2026', w: 44, cover: '#3f7f83', cover2: '#2d5f62', ink: '#f4efe6', jz: 0.18 },
      { title: 'Lisbon & after', date: 'Thursday, 2 April 2026', w: 32, cover: '#d8c3a0', cover2: '#b9a27f', ink: '#2b2620', jz: -0.33 },
      { title: 'Dreams', date: 'Wednesday, 22 April 2026', w: 22, cover: '#4d3347', cover2: '#4d3347', ink: '#f4efe6', jz: 0.05 },
      { title: "Letters I didn't send", date: 'Sunday, 10 May 2026', w: 26, cover: '#d98a6d', cover2: '#c15f3c', ink: '#2b2620', jz: -0.15 },
      { title: 'Slow August', date: 'Saturday, 1 August 2026', w: 52, cover: '#b3842f', cover2: '#b3842f', ink: '#f4efe6', jz: 0.26 },
      { title: 'Notes from the walk', date: 'Tuesday, 9 September 2025', w: 20, cover: '#a7b59a', cover2: '#8a9a7b', ink: '#2b2620', jz: -0.27, note: 'A year ago today', ribbon: true },
      { title: 'September', date: 'Tuesday, 9 September 2026', w: 30, cover: '#2d5f62', cover2: '#2d5f62', ink: '#f4efe6', jz: 0.09 },
    ],
    ghost: { title: 'New entry', note: "Today's page, when you're ready", w: 22 },
    plate: '2026',
    /** the book that says hello when the shelf scrolls into view */
    greet: 10,
  },
} as const
