/** Chrome copy (top bar, popovers, settings, search, toasts, shortcuts, starter book). Sentence case, short, warm. */
export const ui = {
  topbar: {
    wordmark: 'Folio',
    back: 'Back to shelf',
    backToBook: 'Back to book',
    settings: 'Settings',
    pageOf: (n: number, total: number) => `Page ${n} of ${total}`,
    /** Breadcrumb placeholder while an entry has no title yet (rotates by local hour). */
    placeholder: { morning: 'This morning', afternoon: 'This afternoon', night: 'Tonight' },
  },
  save: {
    pending: 'Unsaved changes',
    saving: 'Saving',
    saved: 'Saved just now',
    failed: "Couldn't save — your writing is still here",
    retry: 'Try again',
  },
  search: {
    label: 'Search',
    placeholder: 'Search your entries',
    clear: 'Clear search',
    results: (n: number) => (n === 0 ? 'Nothing matches' : n === 1 ? '1 entry' : `${n} entries`),
    hint: '↑↓ to move, ↵ to open',
    shortcut: '⌘K',
  },
  today: {
    label: 'Today',
    open: "Open today's entry",
    start: "Start today's entry",
    run: (n: number) =>
      ['', '', 'Second day in a row', 'Third day in a row', 'Fourth day in a row', 'Fifth day in a row', 'Sixth day in a row', 'A week in a row'][Math.min(n, 7)],
    yearsAgo: (n: number) => (n === 1 ? 'A year ago today' : `${n} years ago today`),
  },
  cover: {
    title: 'Cover',
    close: 'Close',
    color: 'Color',
    moreTints: 'More tints',
    fewerTints: 'Fewer tints',
    tint: { 0: 'light', 1: 'base', 2: 'deep' } as Record<0 | 1 | 2, string>,
    finish: 'Finish',
    matte: 'Matte',
    cloth: 'Cloth',
    linen: 'Linen',
    picture: 'Picture',
    dropPicture: 'Drop a picture, or choose one',
    dropHere: 'Drop to use as the cover',
    adding: 'Adding picture',
    choose: 'Choose',
    replace: 'Replace',
    remove: 'Remove',
    spine: 'Spine',
    spineTitle: 'Title',
    spineInitial: 'Initial',
    spineBlank: 'Blank',
    thickness: 'Thickness',
    thicknessAuto: 'Auto',
    tooBig: 'That picture is too large to keep',
    notAnImage: "That file isn't a picture",
  },
  context: {
    label: 'Entry options',
    open: 'Open',
    editPage: 'Edit page 1',
    cover: 'Cover…',
    changeDate: 'Change date…',
    duplicate: 'Duplicate',
    remove: 'Remove',
    removed: 'Entry removed',
    duplicated: 'Entry duplicated',
    copySuffix: ' copy',
  },
  date: {
    label: 'Change date',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    today: 'Today',
    movedTo: (month: string) => `Moved to ${month}`,
    weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    weekdaysLong: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  },
  toast: { undo: 'Undo', dismiss: 'Dismiss' },
  settings: {
    title: 'Settings',
    close: 'Close',
    sound: 'Sound',
    sounds: 'Sounds',
    volume: 'Volume',
    motion: 'Motion',
    detents: 'Detents',
    off: 'Off',
    soft: 'Soft',
    firm: 'Firm',
    reduceMotion: 'Reduce motion',
    followSystem: 'Follow system',
    on: 'On',
    hapticsNote: 'Trackpad haptics are not available to web apps on macOS, so Folio uses motion and sound instead.',
    appearance: 'Appearance',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    writing: 'Writing',
    prompts: 'Writing prompts',
    snap: 'Snap to grid',
    journal: 'Your journal',
    export: 'Export as JSON',
    exporting: 'Exporting',
    exportHint: 'Every entry and picture, in one file.',
    import: 'Import JSON',
    importing: 'Importing',
    importDone: (n: number) => `${n} ${n === 1 ? 'entry' : 'entries'} imported`,
    importBad: "That file isn't a Folio export",
    keyboard: 'Keyboard',
    shortcuts: 'Shortcuts',
    danger: 'Danger zone',
    deleteAll: 'Delete everything',
    deleteAllHint: 'Removes every entry and picture on this device.',
    typeToConfirm: 'Type delete to confirm',
    deleteWord: 'delete',
    cancel: 'Cancel',
  },
  shortcuts: {
    title: 'Keyboard shortcuts',
    close: 'Close',
    surfaces: { global: 'Everywhere', shelf: 'Shelf', book: 'Book', page: 'Page' },
    keys: {
      newEntry: 'New entry',
      search: 'Search',
      settings: 'Settings',
      undo: 'Undo',
      redo: 'Redo',
      back: 'Back one level',
      reopen: 'Reopen last closed book',
      sheet: 'Shortcuts',
      moveBooks: 'Move between books',
      jumpMonth: 'Jump a month',
      firstLast: 'First / last book',
      openBook: 'Open book',
      peek: 'Peek label',
      cover: 'Customize cover',
      today: 'Today',
      flip: 'Flip page',
      openPage: 'Open page to edit',
      addPage: 'Add a page',
      pageOptions: 'Page options',
      goToPage: 'Go to page',
      biu: 'Bold, italic, underline',
      strike: 'Strikethrough',
      kinds: 'Title, heading, body, quote',
      triggers: 'Heading / quote, at the start of a line',
      insertPicture: 'Insert picture',
      sticker: 'Sticker',
      dateStamp: 'Date stamp',
      wrap: 'Wrap mode, with a picture selected',
      prevNext: 'Previous / next page',
      deselect: 'Deselect, then back to book',
    },
  },
  starter: {
    title: 'A first page',
    body: [
      'This is a page. Words and pictures sit on a grid of dots, and anything here can be dragged somewhere else. Add a picture from the rail on the left, or paste one in.',
      'When you are ready, start your own entry from the shelf. This book can be removed whenever you like.',
    ],
    imageAlt: 'A warm placeholder picture',
  },
  a11y: {
    topbar: 'Folio',
    popover: 'Popover',
    swatch: (hue: string, tint: string) => `${hue}, ${tint}`,
    swatches: 'Cover color',
    dropzone: 'Cover picture',
    calendar: 'Calendar',
    toasts: 'Notifications',
    menu: 'Entry options',
    thumb: 'Cover picture',
  },
} as const
